### ISSUE TITLE
Bionic not building with umount failure

### ISSUE THREAD

**Issue by pacepace** [newroco/vmbuilder#18]
I've got Xenial building, but it gets hung on umounting when trying to build Bionic.  It cannot umount because of this file in the tmp build structure: /%TMP_BUILD_DIR%/tmp/vmbuilder-grub/tmp%RANDOM% (where %TMP_BUILD_DIR% is usually under /tmp and %RANDOM% is a random string of 6 digits).

I cannot remove that file as root and so far have been unable to find what has it open in lsof or fuser.  So far I have to reboot to be able to delete.  I'm guessing this has to do with a chroot, but I haven't gotten beyond that yet.

For those who wonder, I have the sleep(10) patch in place for both the dev and disk umount, that isn't the issue in this case.

**Comment by pacepace** [comment]
Logs (I included the "E:" at the beginning because it may be a clue.  I need to look at the Xenial install to see if it complains the same way):

2019-04-17 19:57:42,704 INFO    : E: Package 'grub' has no installation candidate
2019-04-17 19:57:42,705 INFO    : Cleaning up
2019-04-17 19:57:52,719 INFO    : umount: /tmp/tmp819B3W/: target is busy.
2019-04-17 19:57:52,719 ERROR   : Process (['umount', '/tmp/tmp819B3W/']) returned 32. stdout: , stderr: umount: /tmp/tmp819B3W/: target is busy.

Traceback (most recent call last):
  File "/usr/local/bin/vmbuilder", line 24, in <module>
    cli.main()
  File "/usr/local/lib/python2.7/dist-packages/VMBuilder/contrib/cli.py", line 228, in main
    hypervisor.install_os()
  File "/usr/local/lib/python2.7/dist-packages/VMBuilder/hypervisor.py", line 70, in install_os
    self.call_hooks('install_bootloader', self.chroot_dir, self.disks)
  File "/usr/local/lib/python2.7/dist-packages/VMBuilder/distro.py", line 69, in call_hooks
    self.cleanup()
  File "/usr/local/lib/python2.7/dist-packages/VMBuilder/distro.py", line 44, in cleanup
    self._cleanup_cbs.pop(0)()
  File "/usr/local/lib/python2.7/dist-packages/VMBuilder/disk.py", line 410, in umount
    run_cmd('umount', self.mntpath)
  File "/usr/local/lib/python2.7/dist-packages/VMBuilder/util.py", line 120, in run_cmd
    raise VMBuilderException, "Process (%s) returned %d. stdout: %s, stderr: %s" % (args.__repr__(), status, mystdout.buf, mystderr.buf)
VMBuilder.exception.VMBuilderException: Process (['umount', '/tmp/tmp819B3W/']) returned 32. stdout: , stderr: umount: /tmp/tmp819B3W/: target is busy.
